---
deployment:
 tasks:
 - export DEPLOYPATH=/home/adminsaul/public_html/
 - /bin/cp -R audio $DEPLOYPATH
 - /bin/cp -R css $DEPLOYPATH
 - /bin/cp -R files $DEPLOYPATH
 - /bin/cp -R fonts $DEPLOYPATH
 - /bin/cp -R img $DEPLOYPATH
 - /bin/cp -R js $DEPLOYPATH
 - /bin/cp -R php $DEPLOYPATH
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp index_sp.html $DEPLOYPATH